### ISSUE TITLE
What is the purpose of get_user_draft_file_webservice.php

### ISSUE THREAD

**Issue by mudrd8mz** [cperves/moodle-block-my_external_privatefiles#8]
Hi. Can you please try to explain the purpose of the file `get_user_draft_file_webservice.php` and especially the function `block_my_external_privatefiles_file_get_user_draft()` call there? The inline comments seem to be a bit misleading (may be they were just copy & pasted from other places?) I can read the function is serving the user's files from the _draft_ area only which is surprising for me.

**Comment by cperves** [comment]
download_external_privatefiles function execute first block_my_external_privatefiles_get_private_files_zip webservice that create a zip file for the user private files in its draft area
I choose drat area in order to not pollute, not inflate the user private file area
May be I don't well understand draft file concept, for me its temporary files while using filepicker and I use them as temporary files

in order to download the resulting private user zip file (user and draft) we can't use webservice/pluginfile.php (case not taken in charge for security reason I suppose), so I choose to implement it in another page  get_user_draft_file_webservice.php to retrieve that generated file.
(an other php file since I always try to minimize moodle core code impact and supposed that user draft file cannot be be served by /webservice/pluginfile.php for security reasons)

I try for your return and advices
Thank You
Céline
